name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        cat id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH Connection
      run: |
        ssh -i id_rsa root@178.253.40.164 "touch win"

      # Replace "command-to-run-on-server" with the actual command you want to execute on the server.

    # Add more steps as needed
