name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa $SSH_HOST >> ~/.ssh/known_hosts
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "cd PROJECT_FOLDER && git pull && docker-compose up --build -d"
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}
        PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
        # You can use SSH_PASSWORD if you prefer password-based authentication
        # SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

