name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        sudo apt-get -y install sshpass

    - name: SSH Connection
      run: |
        sshpass -p 'b7Z+a.Fpa2^9jC' ssh root@178.253.40.164 "touch win"
